config/routes.rb
Rails.application.routes.draw do
  root 'fridge_items#index'
  resources :fridge_items
  resources :recipes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fridge_item.rb
class FridgeItem < ApplicationRecord
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredient
  has_many :fridge_item
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredient
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fridge_items_controller.rb
class FridgeItemsController < ApplicationController
  before_action :set_fridge_item, only: %i[ show edit update destroy ]
  include FindAvailableRecipes
  # GET /fridge_items or /fridge_items.json
  def index
    @fridge_items = FridgeItem.all
    @fridge_item = FridgeItem.new
    @ingredients_data = Ingredient.all
    @ingredient_names = @ingredients_data.pluck(:name)
    @ingredients = @ingredients_data.group_by(&:id)
    @available_recipes = find_available_recipes
  end

  # GET /fridge_items/1 or /fridge_items/1.json
  def show
  end

  # GET /fridge_items/new
  def new
    @fridge_item = FridgeItem.new
  end

  # GET /fridge_items/1/edit
  def edit
  end

  # POST /fridge_items or /fridge_items.json
  def create
    ingredient_names = fridge_item_params[:ingredient_id].split(',').map(&:strip)
    @new_ingredients = {}
    ingredient_names.each do |ingredient_name|
      @ingredient = Ingredient.where("name ILIKE ?", "%#{ingredient_name}%")[0]
      @item_exists = false
      if @ingredient
        @fridge_item = FridgeItem.find_by ingredient_id: @ingredient.id
        if @fridge_item
          respond_to do |format|
            @item_exists = true
            format.html { redirect_to fridge_item, notice: 'Fridge item already exists.' }
            format.js { flash.now[:notice] = "Fridge item already exists." }
            format.json { render :show, status: :created, location: @fridge_item }
          end
        else
          new_params = {ingredient_id: @ingredient.id}
          @fridge_item = FridgeItem.new(new_params)

          respond_to do |format|
            if @fridge_item.save
              @new_ingredients[@ingredient.id] = [@fridge_item, @ingredient.name]
              puts "length: ", ingredient_names.length()
              format.html { redirect_to @fridge_item, notice: 'Fridge item was successfully created.' }
              format.js { flash.now[:notice] = ingredient_names.length()>1 ? "Fridge items successfully added." : "Fridge item successfully added." }
              format.json { render :show, status: :created, location: @fridge_item }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.js { flash.now[:notice] = 'Ingredient does not exist!' }
              format.json { render json: @fridge_item.errors, status: :unprocessable_entity }
            end
          end
        end

      else
        respond_to do |format|
          format.js { flash.now[:notice] = 'Ingredient does not exist!' }
        end
      end
    end
  end

  # PATCH/PUT /fridge_items/1 or /fridge_items/1.json
  def update
    @ingredient = Ingredient.find(@fridge_item.ingredient_id)
    respond_to do |format|
      if @fridge_item.save
        format.html { redirect_to @fridge_item, notice: 'Fridge item was successfully updated.' }
        format.json { render :show, status: :ok, location: @fridge_item }
        format.js { flash.now[:notice] = "#{fridge_item_params[:ingredient_quantity]} #{fridge_item_params[:measurement]} #{@ingredient.name.capitalize} was successfully added to fridge." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fridge_item.errors, status: :unprocessable_entity }
        format.js { flash.now[:notice] = 'Ingredient quantity not added!' }
      end
    end
  end

  # DELETE /fridge_items/1 or /fridge_items/1.json
  def destroy
    @ingredient = Ingredient.find(@fridge_item.ingredient_id)
    @fridge_item.destroy
    respond_to do |format|
      format.html { redirect_to fridge_items_url, notice: "#{@ingredient.name.capitalize} successfully removed from fridge." }
      format.json { head :no_content }
      format.js { flash.now[:notice] = "#{@ingredient.name.capitalize} successfully removed from fridge." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_fridge_item
    @fridge_item = FridgeItem.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def fridge_item_params
    params.require(:fridge_item).permit(:ingredient_id, :ingredient_quantity, :measurement)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]
  include FindAvailableRecipes

  # GET /recipes or /recipes.json
  def index
    @fridge_item_ids = FridgeItem.pluck(:ingredient_id)
    @available_recipes = find_available_recipes
    @recipes = Recipe.paginate(page: params[:page])
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    recipe_ingredients = RecipeIngredient.where(recipe_id: @recipe[:id])
    recipe_ingredient_ids = recipe_ingredients.pluck(:ingredient_id)
    @recipe_ingredients = recipe_ingredients.group_by(&:ingredient_id)
    @ingredients_like_ids = []
    fridge_items = FridgeItem.all
    fridge_items.each do |fi|
      @ingredients_like_ids << find_ingredients_like(fi.ingredient_id)
    end
    @ingredients_like_ids.flatten!
    @ingredients = Ingredient.find(recipe_ingredient_ids)
    @fridge_item_ids = []
    @ingredients.each do |ingredient|
      if @ingredients_like_ids.include?(ingredient.id)
        @fridge_item_ids << ingredient.id
      end
    end
    @fridge_item = FridgeItem.new
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :people_quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fridge_items_helper.rb
module FridgeItemsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/fridge_items/_add_quantity.html.erb
<td>
    <%= button_to fridge_item, action: "delete", method: :delete, remote: true do %>
    Delete
    <% end %>
</td>

app/views/fridge_items/_form.html.erb
<%= form_with(model: fridge_item) do |form| %>
  <% if fridge_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fridge_item.errors.count, "error") %> prohibited this fridge_item from being saved:</h2>

      <ul>
        <% fridge_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ingredient_id %>
    <%= form.number_field :ingredient_id %>
  </div>

  <div class="field">
    <%= form.label :ingredient_quantity %>
    <%= form.text_field :ingredient_quantity %>
  </div>

  <div class="field">
    <%= form.label :measurement %>
    <%= form.text_field :measurement %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fridge_items/create.js.erb
$("#flash").html('<%= j render partial: "layouts/messages" %>');
if (!<%= @item_exists %>) {
    <% @new_ingredients.each do |id, value|%>
        $('#fridge_items_table_body').prepend('<tr id="fridge_item_<%=value[0].id%>">' +
        '<td><%= value[1].capitalize%></td>' +
        '</tr>');
        document.getElementById("fridge_item_<%= value[0].id%>").insertAdjacentHTML("beforeend", "<%= j render partial: 'fridge_items/add_quantity', locals: {fridge_item: value[0]} %>");
    <% end %>
}

app/views/fridge_items/destroy.js.erb
$("#flash").html('<%= j render partial: "layouts/messages" %>');
$('#fridge_item_<%=@fridge_item.id %>').remove();

app/views/fridge_items/edit.html.erb
<h1>Editing Fridge Item</h1>

<%= render 'form', fridge_item: @fridge_item %>

<%= link_to 'Show', @fridge_item %> |
<%= link_to 'Back', fridge_items_path %>

app/views/fridge_items/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_with(model: @fridge_item, id: "new-fridge-item", local: false) do |form| %>
  <div class="form-search">
    <%= form.label :name %>
    <input type="search" placeholder="Add ingredients separated by commas..." data-behavior="autocomplete" id="fridge_item_textbox" name="fridge_item[ingredient_id]">
    <%= form.submit "Add to fridge", class: "btn btn-success" %>
  </div>
<% end %>

<h1>Fridge Items</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody id="fridge_items_table_body">
    <% @fridge_items.each do |fridge_item| %>
      <tr id="fridge_item_<%=fridge_item.id %>">
        <td><%= @ingredients[fridge_item.ingredient_id][0][:name].capitalize %></td>
        <%= render 'add_quantity', fridge_item: fridge_item %>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Available Recipes</h2>

<table>
  <thead>
  <tr>
    <th>Recipe Name</th>
    <th>For</th>
    <th>Link</th>
  </tr>
  </thead>
<% @available_recipes.each do |recipe| %>

    <tr>
      <td><%=recipe[:name] %></td>
      <td><%=recipe.people_quantity %></td>
      <td><%= link_to 'Show', recipe_path(recipe) %></td>
    </tr>
<% end %>
</table>

app/views/fridge_items/new.html.erb
<h1>New Fridge Item</h1>

<%= render 'form', fridge_item: @fridge_item %>

<%= link_to 'Back', fridge_items_path %>

app/views/fridge_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ingredient:</strong>
  <%= @fridge_item.ingredient_id %>
</p>

<p>
  <strong>Ingredient quantity:</strong>
  <%= @fridge_item.ingredient_quantity %>
</p>

<p>
  <strong>Measurement:</strong>
  <%= @fridge_item.measurement %>
</p>

<%= link_to 'Edit', edit_fridge_item_path(@fridge_item) %> |
<%= link_to 'Back', fridge_items_path %>

app/views/fridge_items/update.js.erb
$("#flash").html('<%= j render partial: "layouts/messages" %>');
$('#quantity_<%= @fridge_item[:id]%>').html(<%= @fridge_item[:ingredient_quantity]%>);

app/views/layouts/_header.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarCenteredExample"
      aria-controls="navbarCenteredExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div
      class="collapse navbar-collapse justify-content-center"
      id="navbarCenteredExample"
    >
      <!-- Left links -->
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to "Fridge", root_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%=link_to "Recipes", recipes_path, class: "nav-link" %>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>

app/views/layouts/_messages.html.erb
<div data-alert class="alert-box">
  <%= notice %>
  <a href="#" class="close">&times;</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinnerMenu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <div id="flash">
    <% if notice.present? %>
      <%= render partial: "layouts/messages" %>
    <% end %>
  </div>
  <%= yield %>
  <%= render "layouts/footer" %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :people_quantity %>
    <%= form.number_field :people_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<h2>Available Recipes</h2>
<table>
  <thead>
  <tr>
    <th>Recipe Name</th>
    <th><i class="fas fa-user-friends"></i></th>
  </tr>
  </thead>
  <% @available_recipes.each do |recipe| %>

    <tr>
      <td><div class="check"></div> <%=recipe[:name] %></td>
      <td><%=recipe.people_quantity %></td>
    </tr>
  <% end %>
</table>

<h2>All Recipes</h2>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th><i class="fas fa-user-friends"></i></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.people_quantity %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<h2 id="recipe_name"> <%= @recipe.name %></h2>

<p>
  <strong>People quantity:</strong>
  <%= @recipe.people_quantity %>
</p>
<h4>Ingredients</h4>
<div class="ingredients_list">
  <table>
    <thead>
    <tr>
      <th>Ingredient</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td id="ingredient_<%= ingredient.id%>">
          <% if @fridge_item_ids.include? ingredient.id %>
            <div class="check" id="check_<%=ingredient.id %>"></div>
          <% end %>
          <%recipe_ingredient = @recipe_ingredients[ingredient.id][0] %>
          <%= recipe_ingredient[:needed]%> <%= recipe_ingredient[:measurement]%> <%= ingredient[:preposition] %><%= ingredient[:name] %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>